### ISSUE TITLE
Annoying deprecated `ActionUpdateThread.OLD_EDT` warning!

### ISSUE THREAD

**Issue by Inmoresentum** [yelog/vim-flash#27]
Easy to fix deprecated `ActionUpdateThread.OLD_EDT`. Attaching the stack trace below :)

```log
    com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.yelog.ideavim.flash.SearchAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: org.yelog.ideavim.flash]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

BTW Good work with the plugin :+1:

**Comment by yelog** [comment]
Thank you for your feedback. This issue will be fixed in an upcoming update.

**Comment by Inmoresentum** [comment]
Thank you for your response.

**Comment by yelog** [comment]
The latest version has already fixed the issue. Please upgrade to version 0.0.4 and try again.
