### ISSUE TITLE
Exception throwed with goland 2024.2.1

### ISSUE THREAD

**Issue by egolearner** [yelog/vim-flash#31]
Thanks for your great plugin. It seems that deprecated feature is used by this plugin and hopefully you can fix it sometime.

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 
'org.yelog.ideavim.flash.SearchAction' must override `getActionUpdateThread()` and chose EDT or BGT. 
See ActionUpdateThread javadoc. [Plugin: org.yelog.ideavim.flash]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by yelog** [comment]
Same issue https://github.com/yelog/vim-flash/issues/27

Will be fixed in the next version

**Comment by yelog** [comment]
The latest version has already fixed the issue. Please upgrade to version 0.0.4 and try again.
